name: Backpack
author: Tocoolmh58
version: ${project.version}
main: de.tocoolmh58.backpack.Main
api-version: 1.17
description: Ein einfaches Backpack Plugin
commands:
  backpack:
    aliases:
      - bp
      - rucksack
    description: Öffnet deinen Rucksack